from typing import Any, List, Optional
from pydantic import BaseModel, Field
from datetime import datetime


class MessageRequest(BaseModel):
    """
    Represents a message in a chat completion.
    """

    role: Optional[str] = Field(None, description="The role of the message", examples=["user", "assistant", "system"])
    content: Optional[str] = Field(None, description="The content of the message")


class ChatCompletionRequest(BaseModel):
    """
    Represents a chat completion request. Starting a new chat or continuing a previous chat.
    """

    completion_id: Optional[str] = Field(
        None,
        description="The unique identifier for the chat completion. When starting a new chat, this will be a new UUID. When continuing a previous chat, this will be the same as the previous chat completion id.",
    )
    model: Optional[str] = Field(None, description="The model to use for the chat completion")
    messages: Optional[List[MessageRequest]] = Field(None, description="The messages to use for the chat completion")
    stream: Optional[bool] = Field(None, description="Whether to stream the chat completion")


class MessageResponse(BaseModel):
    """
    A chat completion message generated by the model.
    """

    message_id: Optional[str] = Field(None, description="The unique identifier for the message")
    role: Optional[str] = Field(None, description="The role of the message", examples=["user", "assistant", "system"])
    content: Optional[str] = Field(None, description="The content of the message")
    figure: Optional[dict[str, Any]] = Field(None, description="The figure data to be visualized")
    created_date: Optional[datetime] = Field(None, description="The date and time the message was created")


class ChoiceResponse(BaseModel):
    finish_reason: Optional[str] = Field(
        None,
        description="The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence, `length` if the maximum number of tokens specified in the request was reached, `content_filter` if content was omitted due to a flag from our content filters",
        examples=["stop", "length", "content_filter"],
    )
    index: Optional[int] = Field(None, description="The index of the choice in the list of choices.")
    message: Optional[MessageResponse] = Field(None, description="The message to use for the chat completion")
    # logprobs: str = None # not implemented yet


class ChatCompletionResponse(BaseModel):
    """
    Represents a chat completion response returned by model, based on the provided input.
    """

    completion_id: Optional[str] = Field(None, description="The unique identifier for the chat completion")
    choices: Optional[List[ChoiceResponse]] = Field(None, description="A list of chat completion choices.")
    created: Optional[int] = Field(None, description="The Unix timestamp (in seconds) of when the chat completion was created.")
    model: Optional[str] = Field(None, description="The model used for the chat completion")
    # not implemented yet
    # service_tier: Optional[ServiceTier] = ServiceTier.AUTO
    # system_fingerprint: Optional[StrictStr] = Field(default=None, description="This fingerprint represents the backend configuration that the model runs with.  Can be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism. ")
    # object: StrictStr = Field(description="The object type, which is always `chat.completion`.")
    # usage: Optional[CompletionUsage] = None


class ChatCompletionStreamResponse(ChatCompletionResponse):
    """
    Represents a chat completion stream response returned by model, based on the provided input.
    """


class PlotRequest(BaseModel):
    """
    Represents a plot request for a given message to be visualized.
    """

    message_id: str = Field(
        ...,
        description="The unique identifier for the message that the plot is for",
    )


class PlotResponse(BaseModel):
    """
    Represents a plot response.
    """

    plot_id: str = Field(..., description="The unique identifier for the plot")
    completion_id: str = Field(
        ...,
        description="The unique identifier for the chat completion that the plot is for",
    )
    message_id: str = Field(
        ...,
        description="The unique identifier for the message that the plot is for",
    )
    figure: dict = Field(..., description="The figure data to be visualized")
